---
title: "Cyclones"
date: July, 2026
output: github_document
---
# Introduction
For workflow vignettes, see the [documention website](https://bbranoff.github.io/Cyclones/)

Cyclones is a collection of R utilities for producing variable temporal and spatial resolution gridded and time-stacked representations of historic tropical cyclone wind, precipitation, and storm surge. Processing can be done sequentially for low and moderate resolution products, or in parallel for high resolution. 

For now, Cyclones is hosted only here on Github and can be installed as follows:

```{r install,eval=FALSE}
## install.packages("remotes")
remotes::install_github("BBranoff/Cyclones")

## for the development version (unstable)
remotes::install_github("BBranoff/Cyclones@development")
```

# Highlights
* Produce raster images of cyclone winds, rains, and storm surge, either at specific times or as aggregate
  * Choose data sources and temporal and spatial resolutions

* Ingest storm tracks and wind and pressure extents from IBTrACS
  * Consolidate data across meteorological agencies
  
* For winds:
  * Choose among Boose, Holland, Willoughby, or Thin Plate Spline methods
  * Model missing extents from similar storms
  * Calculate maximum sustained winds, wind direction, and power
  * Compare calculated winds against Hurricane Hunter drop sondes
  
* For rainfall:
  * Choose among ERA5, MSWEP, or GPM sources
  * Calculate PRE-storm and storm precipitation
  
* For storm surge:
  * Conglomerate across measured (NOAA & USGS), and modeled (CMIP6) water levels
  * Compare against SRTM elevation to approximate water depth 
    
# Future Implementation Ideas
* Integrate NISAR data for:
  * Soil moisture
  * Flooding extent
  * Biomass loss
* Integrate STAR NESDIS SAR for windspeed comparisons
* Integrate LANDSAT for NDVI
* Integrate available LiDAR or NAIP clouds for canopy structure
* Integrate SLOSH for storm surge
