---
title: "Rains"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Rains}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Get Precipitation Products
The Cyclones package can also ingest and process precipitation data for all storms after 1940. There are three potential sources for the data: [the European Space Agency's ERA5 (ecmwf)](https://cds.climate.copernicus.eu/datasets/reanalysis-era5-single-levels), [the National Aeronautics and Space Administration's (NASA) Global Precipitation Measurement Mission (gpm)](https://gpm.nasa.gov/missions/GPM), and [the Multi-Source Weighted-Ensemble Precipitation (mswep)](https://www.gloh2o.org/). All data sources require some sort initial registration before they can be accessed via the api, as well as additional packages for extracting and assembling the data. They are global, hourly or three-hourly data at ~25 and 10 km resolution. The get_precip function will request data from the source (default is ecmwf), download it into a given directory (if specified), and then create storm specific gridded precipitation outputs. 

Unlike wind, cyclone precipitation patterns are often preceded by "predecessor rain events" [(PREs)]("https://doi.org/10.1175/2010MWR3243.1"), in which moist tropical air is trapped and lifted by a high pressure system in front of the oncoming cyclone, where it then falls as significant precipitation around 36 hours before the arrival of cyclone derived rainfall. Therefore, 'get_precip()' will accept a numerical "prestorm" argument specifying the number of hours before the arrival of a cyclone for which to also gather precipitation. A value of TRUE will also be accepted and will default to 48 hours.  In these cases, the results will be separated into "storm" and "prestorm" rasters.   
