#' Generate 2D storm surge rasters for a given storm
#'
#'`get_surge()` will accept the output of 'get_storms()' and return a single layer raster representing the maximum storm surge during the life of the storm.
#' Storm surge is a product of surface elevation and water levels. It is calculated as the maximum water depth, in meters, over land only where the elevation is
#' greater than the mean high tide from the previous year. Surface elevation comes from NASA's Shuttle Radar Topography Mission (SRTM), which
#' has global coverage at 30 m resolution. These will be applied to all storms and only need to be downloaded once per location. They may also be used
#' for wind topography interactions in future package versions. Water levels come from three sources and these sources mostly determine the quality of
#' the final surge product. In coastal areas of the United States, data from the National Oceanic and Atmospheric Administration (NOAA) and the United States
#' Geological Survey (USGS) provide very accurate observations with good geographic coverage for relatively recent storms.
#' The European Union's Coupled Model Intercomparison Project (CMIP6) provides global coverage back to 1850 but as an ensemble model product, the values
#' are less accurate that those from NOAA and USGS. All three sources are used to interpolate water levels between observation locations, but preference is
#' given to usgs and noaa values when available.
#' The spatial resolution of the surge raster, for now, is limited to that of the elevation data.
#'
#' @param storm A set of storm tabular data generated by 'get_storms()'. If not used with an apply function, only the first storm will be processed.
#' @param dpath The download path of the sourced elevation and water level data. Raw files will be stored here and then searched for here before
#' downloading from the web. An "./Elevation/" and "./Water Levels/" directory will be created for each group of data.
#' @param cpus The number of cpus to use in parallel processing.
#' @examples
#' Sandy <- get_storms(name='Sandy',season=2012)
#' Sandy_surge <- get_surge(Sandy,dpath="I:/")
#' ###  focus on New York
#' Sandy_surge_NYC <- crop(Sandy_surge,ext(c(-75,-73.5,40,41)))
#' plot(Sandy_surge_NYC)
#'
#' ##  A non-USA/historical storm
#' ##  will rely entirely on CMIP6 model output
#' Nargis <- get_storms(name='Nargis',season=2008)
#' Nargis_surge <- get_surge(Nargis,dpath="I:/")
#' Nargis_surge_Myanmar <- crop(Nargis_surge,ext(c(90,98,13.5,19)))
#' plot(Nargis_surge_Myanmar)
#' @importFrom terra crs as.points project focal patches freq values
get_surge <- function(storm,dpath=NULL,todir=NULL,cpus=NULL,overwrite=FALSE,returnpoints=TRUE,usgskey=NULL,loadrasts=FALSE){
  if (!is.null(cpus)) on.exit(snowfall::sfStop())
  if (class(storm)[1]%in% c("vctrs_list_of","list","tbl_df","sf")){
    if (is.null(dim(storm))){
      #if (!class(storm)[1]=="vctrs_list_of") stop("Unknown data source. Did you use lapply on a single storm?")
      options(warn=1)
      warning("Only first storm will be used. Use lapply or a parallel equivalent to repeat for multiple storms.")
      storm <- storm[[1]]
      options(warn=0)
    }
  }
  if (!is.null(dpath)){
    if (substr(dpath,nchar(dpath),nchar(dpath))!="/") dpath=paste0(dpath,"/")
    if (!dir.exists(dpath)) stop("Specified 'dpath' directory not found.")
  }else{
    dpath=paste0(tempdir(),"/")
  }
  if (!is.null(todir)){
    if (!substr(todir,nchar(todir),nchar(todir))=="/") todir=paste0(todir,"/")
    if (!dir.exists(todir)) stop("Specified todir directory not found.")
    if (overwrite==FALSE) cat(paste0("Saving to: ",todir,". Overwrite set to FALSE, existing files will be SKIPPED.","\n"))
    else cat(paste0("Saving to: ",todir,". Overwrite set to TRUE, existing files will be REPLACED.","\n"))
  }
  dirs <- list.dirs(dpath,recursive=FALSE)
  elev_dir <- dirs[grep("elev",dirs,ignore.case = TRUE)]
  WL_dir <- dirs[grep("level",dirs,ignore.case = TRUE)]
  if (length(elev_dir)==0){elev_dir <- paste0(dpath,"Elevation");dir.create(elev_dir)}
  if (length(WL_dir)==0){WL_dir <- paste0(dpath,"Water Levels");dir.create(WL_dir)}
  storm$LAT <- as.numeric(storm$LAT);storm$LON <- as.numeric(storm$LON)
  custCRSall <- paste0("+proj=laea +lat_0=",round(mean(storm$LAT,na.rm=TRUE))," +lon_0=",round(mean(storm$LON,na.rm=TRUE))," +lat_1=",ceiling((max(storm$LAT,na.rm=TRUE)-min(storm$LAT,na.rm=TRUE))/6),
                       " +lat_2=",ceiling(5*(max(storm$LAT,na.rm=TRUE)-min(storm$LAT,na.rm=TRUE))/6)," +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs +type=crs")
  storm <- st_as_sf(storm,coords=c("LON","LAT"),crs=4326)
  storm <- st_transform(storm,custCRSall)
  elevs <- get_srtm(storm,dpath=elev_dir)
  if (is.null(elevs)) return(NULL)
  tiles <- elevs$tiles
  elevs <- elevs$elevs
  surges_cmip6 <- get_cmip(storm,dpath=WL_dir)
  #surges_surgedat <- get_surgedat(storm)
  surges_noaa <- get_noaaWL(storm,dpath=WL_dir)
  surges_usgs <- get_usgs(storm,dpath=WL_dir,key=usgskey)
  surges_cmip6 <- surges_cmip6 |> rename(HT=MHHW)|> select(any_of(c(maxWL = "waterlevel")), everything())
  surges_agg <- surges_cmip6 |> mutate(source="cmip6") |> select(any_of(c("maxWL","HT","source")))
  ####  usgs needs to correct for MSL
  if (!is.null(surges_usgs)){
    surges_usgs_agg <- surges_usgs |>  group_by(monitoring_location_id) |> summarise(maxWL=max(value-MSL,na.rm=TRUE),HT=max(MHT-MSL,na.rm=TRUE))|>rename(station_id=monitoring_location_id)
    surges_agg <- bind_rows(surges_agg,surges_usgs_agg|> mutate(source="usgs",rastsource="usgs&noaa") |> select(station_id,maxWL,HT,source))
  }
  if (!is.null(surges_noaa)){
    surges_noaa_agg <- surges_noaa |> group_by(stationId) |> summarise(maxWL=max(value,na.rm=TRUE),HT=max(meanHT,na.rm=TRUE))|>mutate(stationId=as.character(stationId))|>rename(station_id = stationId)
    surges_agg <- bind_rows(surges_agg,surges_noaa_agg|> mutate(source="noaa",rastsource="usgs&noaa") |> select(station_id,maxWL,HT,source))
  }
  if (is.null(surges_noaa)&is.null(surges_usgs)){
    surges_uhslc <- get_uhslc(storm,dpath=WL_dir)
    if (!is.null(surges_uhslc)) {
      surges_uhslc <- surges_uhslc |> group_by(UHid) |> summarise(maxWL=max(relWL,na.rm=TRUE),HT=max(MHT,na.rm=TRUE))
      surges_agg <- bind_rows(surges_agg,surges_uhslc|> mutate(source="uhslc") |> select(maxWL,HT,source))
    }
    surges_surgedat <- get_surgedat(storm,surges_cmip6)
    if (!is.null(surges_surgedat)&&nrow(surges_surgedat)>0) surges_agg <- bind_rows(surges_agg,surges_surgedat|> mutate(source="surgedat") |> select(maxWL,source))
    #### the uhslc and surgedat data only really work when combined with cmip6
    ####  otherwise there are not enough data points for a good interpolation
    ####  need to prioritize the non-cmip6 data when points are close
    if (nrow(surges_agg|>filter(source!="cmip6"))>0){
      dist <- sf::st_distance(surges_agg|>filter(source=="cmip6"),surges_agg|>filter(source!="cmip6"))
      distmins <- apply(dist,1,min)
      exclude <- which(surges_agg$source=="cmip6")[which(distmins<100000)]
      surges_agg$maxWL[exclude] <- NA
      surges_agg$rastsource=rname="cmip6&others"
    }else{
      ###  if there are no cmip6 data an no other data, return NULL
      if ("maxWL" %in% names(surges_cmip6)){  surges_agg$rastsource=rname="cmip6"
      }else {
        options(warn=1)
        warning("No water level observations available, cannot compute surge. Returning NULL.")
        options(warn=1)
        return(NULL)
      }

    }

  }else{
    surges_agg$rastsource=rname="usgs&noaa&cmip6"
  }
  #if (exists("surges_noaa_agg")&exists("surges_usgs_agg"))surges_noaa_usgs <- bind_rows(surges_noaa_agg |> mutate(source="noaa")|>select(maxWL,HT,source),surges_usgs_agg|> mutate(source="usgs") |> select(maxWL,HT,source))
  #surges_surgedat_agg <- surges_surgedat |> group_by(geometry)
  r <- rast(ext(st_transform(tiles,4326)), res=0.1)
  terra::crs(r) <- terra::crs("epsg:4326")
  r.points <- suppressWarnings(terra::as.points(r))
  ###  create a background of the inerpolated maximum water height
  #surges <- list(cmip6=surges_cmip6,noaa_usgs=surges_noaa_usgs)
  int_rs <- list()
  for (var in c("maxWL","HT")){
    ###  inverse distance weighted model to interpolate between water levels
    ##  by source
    for (src in c("cmip6","noaa|usgs")){
      if (any(grepl(src,surges_agg$source))){
        idw_mod <- gstat::gstat(formula = as.formula(paste(var,1,sep="~")), data = surges_agg|>ungroup()|>filter(grepl(src,rastsource))|>filter(!is.na(!!rlang::sym(var))),
                                set = list(idp = 2))
        idw_pred <- predict(idw_mod, st_as_sf(r.points),debug.level = 0)
        idw_rast <- rasterize(vect(idw_pred), r, field = "var1.pred")
        names(idw_rast) <- paste0(var,"_",src) #paste(names(surges)[s],var,sep="_")
        int_rs <- append(int_rs,idw_rast)
      }
    }
  }
  remove(idw_mod ,idw_pred,idw_rast)
  if (!is.null(cpus)){
    on.exit(stopCluster(cl))
    cl <- initiatepar(cpus=cpus,type="surge")
    elevs <- lapply(elevs,wrap)
    int_rs <- wrap(int_rs)
    ##  split the process into parts, one for each worker
    ##  benchmarking shows standard unsplit parallel is fastest
    #elevs <- split(elevs,cut(seq_along(elevs),cpus))
    #surgerasts <- sfLapply(seq_along(elevs),function(x){lapply(seq_along(elevs[[x]]),surgeapply,elvs=elevs[[x]],srges=surges_agg,s_int=int_rs,tls=tiles)})
    #surgerasts <- unlist(surgerasts)
    #surgerasts <- sfLapply(seq_along(elevs),surgeapply,elvs=elevs,srges=surges_agg,s_int=int_rs,tls=tiles)
    surgerasts <- pblapply(seq_along(elevs),surgeapply,elvs=elevs,srges=surges_agg,s_int=int_rs,tls=tiles,cl=cl)
    }else{
    surgerasts <- lapply(seq_along(elevs),surgeapply,elvs=elevs,srges=surges_agg,s_int=int_rs,tls=tiles)
  }
  cat("\r", paste(rep(" ", 50), collapse=""), "\r")
  surgerasts <- Filter(Negate(is.null), surgerasts)
  if (length(surgerasts)>0){
    surgerasts <-  lapply(surgerasts, unwrap)
    if (length(surgerasts)>1) surgerast <- round(do.call(mosaic,surgerasts),3)
    else surgerast <- round(surgerasts[[1]],3)
    names(surgerast)=paste0("maxsurgedepth.m_",rname)
    if (!is.null(todir)){
      tofile <- paste0(todir,gsub("[^A-Za-z0-9._-]", "-", unique(storm$ID)),"_surge.tif")
      if (!file.exists(tofile)|overwrite) writeRaster(surgerast,tofile,overwrite=overwrite)
      if (returnpoints){
        surges_agg$lon <- st_coordinates(surges_agg)[,1]
        surges_agg$lat <- st_coordinates(surges_agg)[,2]
        tofile <- paste0(todir,gsub("[^A-Za-z0-9._-]", "-", unique(storm$ID)),"_surgepoints.csv")
        if (!file.exists(tofile)|overwrite) write.csv(st_drop_geometry(surges_agg),tofile,row.names=FALSE)
      }
      if (loadrasts) return(list(rast=surgerast,points=surges_agg))
    }else{
      return(list(rast=surgerast,points=surges_agg))
    }
  }else{
    if (!is.null(todir)&returnpoints){
      tofile <- paste0(todir,gsub("[^A-Za-z0-9._-]", "-", unique(storm$ID)),"_surgepoints.csv")
    if (!file.exists(tofile)|overwrite) write.csv(st_drop_geometry(surges_agg),tofile,row.names=FALSE)
    }else{
      return(st_drop_geometry(surges_agg))
    }
  }

}
surgeapply <-  function(x,elvs,srges,s_int,tls){
  el <- unwrap(elvs[[x]])
  el <- focal(el,matrix(1,nrow=3,ncol=3),fun="mean",na.policy="all")
  s_int <- unwrap(s_int)
  ##  anyway to check if no cells would be inundated?
  ##  can avoid the lengthy calculations
  #test <- el

  #test[test>max(minmax(maxWL)[2,])] <- NA
  #test[test<max(minmax(meanHT)[2,])] <- NA
  ###  if none of the elevations are lower than the mean HT, skip the tile, none of them will be abnormally flooded
  #if(all(is.na(values(test)))){cat("\rCalculating surge: %",round(100*x/length(elvs),1));return(NULL)}
  ####  calculate distance from the border of the tile to all points
  #noaa_dst  <- as.numeric(sf::st_distance(tls[x,],srges$noaa|>distinct(geometry)))
  noaa_usgs_dst <- as.numeric(sf::st_distance(tls[x,],srges|>filter(grepl("noaa|usgs",source))|>distinct(geometry)))
  ###  if there are no usgs or noaa gauges within 100km, use the cmip data
  if (min(noaa_usgs_dst,na.rm=TRUE)>100000){
    s_int <- s_int[[grepl("cmip",names(s_int))]]
    # r <- rast(ext(st_transform(tls,4326)), res=0.1)
    # terra::crs(r) <- terra::crs("epsg:4326")
    # r <- crop(r,el)
    # r <- extend(r,c(1,1,1,1))
    # r.points <- suppressWarnings(as.points(r))
    # ###  create a mean HT raster
    # idw_mod <- gstat::gstat(formula = HT ~ 1, data = srges|>filter(source=="cmip6"), set = list(idp = 2))
    # idw_pred <- predict(idw_mod, st_as_sf(r.points),debug.level = 0)
    # idw_raster <- rasterize(vect(idw_pred), r, field = "var1.pred")
    # meanHT <- project(idw_raster,el)
    # ### the cmip data is very big, only worth doing the interpolation by tile
    # idw_mod <- gstat::gstat(formula = maxWL ~ 1, data = srges|>filter(source=="cmip6"), set = list(idp = 2))
    # idw_pred <- predict(idw_mod, st_as_sf(r.points),debug.level = 0)
    # idw_raster <- rasterize(vect(idw_pred), r, field = "var1.pred")
    # s_int <- project(idw_raster,el)
    # maxWL <- s_int
    #surge[el>surge] <- NA
  }else{
    s_int <- s_int[[grepl("noaa|usgs",names(s_int))]]
    ##  othwerwise
    ###  get the mean of the maximum interpolated water level from noaa and usgs
    #s_int <- s_int$maxWL#app(s_int$maxWL,mean)
    #s_int <- project(s_int,el)
  #  surge <- maxWL#s_int
  }
  maxWL <- project(crop(s_int[[grepl("maxWL",names(s_int))]],el),el)
  meanHT <- project(crop(s_int[[grepl("HT",names(s_int))]],el),el)
  ###  if the elevation is bigger than the water level, its too high to be flooded
  maxWL[el>maxWL] <- NA
  #el2 <- el
  #el2[el2==1] <- 0
  surge=maxWL-el
  ###  if the elevation is less than the meanHT, no need to map it, it floods frequently
  surge[el<meanHT] <- NA
  #surge[surge>maxval] <- maxval
  if (!all(is.na(values(surge)))){
    ###  fill in 'gaps'
    surge <- focal(surge, matrix(1,5,5), fun=mean, na.policy="only", na.rm=TRUE)
    ###  remove isolated islands
    patches_surge <- patches(surge, directions = 8, allowGaps = FALSE)
    patch_freq <- freq(patches_surge)
    small_patches <- patch_freq[patch_freq$count <= 25, "value"]
    surge <- mask(surge,terra::match(surge,small_patches),inverse=TRUE)
    ###  now smooth
    surge <- focal(surge, matrix(1,5,5),fun="mean",na.rm=TRUE,na.policy="omit")
    surge[surge<0] <- NA
  }else{ cat("\rCalculating surge: %",round(100*x/length(elvs),1));return(NULL)}
  cat("\rCalculating surge: %",round(100*x/length(elvs),1))
  wrap(surge)
  #}
}
