#' Generate 2D wind fields for a storm
#'
#'`get_wind()` will accept the output of 'make_extents()' and return a series of raster stacks, one for each time step, representing the desired wind related variables. The temporal resolution of the rasters will be the same as that
#' of the input wind extents.
#'
#' @param stormextent A set of storm wind extents generated by the 'make_extents()' function. If not used with an apply function, only the first storm will be processed.
#' @param s_res The spatial resolution, in meters, of the desired output. Higher resolutions (lower numbers) will take significantly longer and parallel processing may be warranted below
#' 10000 meters.
#' @param methods One or all of 'tps', 'boose', 'willoughby', or 'holland'. See details below. 'all' will perform all of the methods.
#' @param cpus How many cpu cores to assign for parallel processing. Recommended to verify available cores before using.
#' @param todir The target directory for final rasters. If not provided, rasters will be loaded in memory. Thus, highly recommended for high resolution products or for batch processing.
#' @param overwrite Should existing files in 'todir' be overwritten. If not, those will be skipped.
#' @param smooth Should a smoothing function be applied, analagous to that applied to StormR products.
#' @param eye_option How the eye wall is processed when creating rasters. See details.
#' @returns Raster stacks, one for each time step in the output of 'make_extents()', with the spatial resolution of 's_res' and the spatial extent of the cumulative radius of the last
#' closed isobar (ROCI), representing the maximum sustained wind in meters per second, the wind direction in degrees, and the total power in kilowatts exerted by the maximum sustained
#' wind on 1 square meter of a surface for the duration of the time step.
#' @details Maximum sustained wind is defined differently across agencies and methods, but is generally summarised as the average wind speed sustained over a given period of time, the interval.
#' Intervals vary by agency, with 10-minutes being the most common and with USA agencies utilizing 1-minute intervals. In cyclones, wind speeds are highest towards the center and decrease
#' non-linearly as a function of the distance from the center. Several theoretical models have been proposed to generalize this relationship and can be utilized in 'get_wind()'. These functions
#' utilize the storm's location and its maximum wind speed and pressure differential to predict wind speeds anywhere within the footprint.
#' [Holland, 1980]("https://doi.org/10.1175/1520-0493(1980)108<1212:AAMOTW>2.0.CO;2") describes this as a function of the pressure field and the radius of maximum wind.
#' [Boose, 2004]("https://harvardforest.fas.harvard.edu/publications/pdfs/Boose_Chapter_HurricanesTyphoons_2004.pdf") expands upon this, introducing asymmetry and differential interactions
#' over land and water. [Willoughby, 2006]("https://doi.org/10.1175/MWR3106.1") is a piecewise function that stitches together two models, one for the inner region of the storm and another for
#' the outer region. The algorithms for these methods were adapted from the StormR package. Finally, an interpolation method, Thin Plate Spline, can be applied to the extents constructed by
#' 'make_extents()'. Although computationally more demanding, TPS is shown here to best generalize observations from drop sondes.
#' @examples
#' # One storm, coarse resolution, with native extents only and with consolidated values.
#' Helene <- get_storms(name='HELENE',season=2024)
#' Helene_extents <- make_extents(Helene)
#' Helene_winds <- get_wind(Helene_extents,methods='all')
#' Helene_winds <-rast(lapply(Helene_winds,unwrap))
#' Helene_msw <- Helene_winds[[grep("msw",names(Helene_winds))]]
#' plot(Helene_msw[[c(grep("tps",names(Helene_msw))[1],grep("boose",names(Helene_msw))[1],grep("holland",names(Helene_msw))[1],grep("willoughby",names(Helene_msw))[1])]])
#' ##  take the maximum wind speed across the storm's lifetime
#' Helene_msw.max <- tapp(Helene_msw,c(ifelse(grepl("tps",names(Helene_msw)),"tps",ifelse(grepl("boose",names(Helene_msw)),"boose",ifelse(grepl("holland",names(Helene_msw)),"holland","willoughby")))),fun="max",na.rm=TRUE)
#' plot(Helene_msw.max)

#' @importFrom sf st_coordinates st_as_sfc st_sf st_crs st_shift_longitude st_geometry_type
#' @importFrom terra rast res ext extend approximate setValues shift resample app allNA ifel time rotate wrap sources crs project
get_wind <- function(stormextent,s_res=20000,methods=NULL,cpus=NULL,
                     todir=NULL,overwrite=FALSE,smooth=FALSE,eye_option="maxwind",loadrasts=FALSE){
  if (!is.null(cpus)){parallel <- TRUE;on.exit(sfStop())}else{parallel <- FALSE}
  ###  if the supplied input are directories of previously saved rasters, load those
  if (class(stormextent)[1]=="character") return(load_wind(stormextent,todir,loadrasts))
  ###  this must be done before the directory/file check
  ###  if multiple storms are passed to the function,
  if (is.null(dim(stormextent))){
    if (class(stormextent)=="numeric") stop("Unknown data source. Did you use lapply on a single storm?")
    options(warn=1)
    warning("More than one storm in data. Only first will be used. Use lapply or a parallel equivalent to repeat for multiple storms.")
    stormextent <- stormextent[[1]]
    options(warn=0)
  }else{
    if (!"sf" %in% class(stormextent)) error("Input is not a spatial storm extent. Use 'make_extents()' to create storm extent.")
  }
  if (is.null(dim(stormextent))){
    if ("linestrings" %in% names(stormextent)) stormextent <- stormextent$linestrings
    else stormextent <- stdh_cast_substring(stormextent)
  }else if ("POLYGON" %in% unique(st_geometry_type(stormextent))){
    stormextent <- stdh_cast_substring(stormextent)
  }
  ##  if the call to the function was not direct "get_wind()" or wrapped in an lapply for sequential processing, its likely a parallel wrapper has been used
  ##  in this case, further parallelization is not supported
  ##  check for external parallelization
  ex_parallel <- any(unlist(lapply(sys.calls(), function(cal) {
    as.character(cal[[1]]) %in% c("slaveLoop", "%dopar%","workLoop")
  })))
  if (parallel){
    if (ex_parallel) stop("Another wrapper function detected. Is parallel processing already implemented at the storm level? Nested parallel operations  not currently supported.")
    if (!"snowfall" %in% installed.packages()) stop("package 'snowfall' not detected but necessary for internal parallel operations.")
    cl <- initiatepar(cpus)
  }
  if(any(methods=="all")) methods=c("TPS","Willoughby","Boose","Holland")
  stormextent <- check_extents(stormextent,methods,s_res)
  if (is.null(stormextent)) return(NULL)
  rTempP <- stormextent$rTempP
  methods <- stormextent$meths
  stormextent <- stormextent$stormextent
  options(warn=0)
  if (!is.null(todir)){
    if (!substr(todir,nchar(todir),nchar(todir))=="/") todir=paste0(todir,"/")
    if (!dir.exists(todir)) stop("Specified todir directory not found.")
    t_res <- difftime(stormextent|>filter(location=="track points")|>pull(date),lead(stormextent|>filter(location=="track points")|>pull(date)),units="mins")|>as.numeric()|>unique()|>abs()|>mean(na.rm=TRUE)
    todir <-  paste0(todir,unique(stormextent$name),unique(format(stormextent$date,"%Y")),"_",s_res,"_",t_res,"_WIND")
    if (!dir.exists(todir)) dir.create(todir)
  }
  ####  also create break to aggregate the files if resolution is too high
  ##  create template raster for all methods to project upon
  ##  TPS just needs a projected crs
  ##  must use a shifted(rotated) crs to avoid the antimeridian for theoretical models
  ##  if the ROCI is missing, assume it is around 500km
  rTemps <- list(rTempG=rotate(project(rTempP,"epsg:4326")),rTempP=rTempP)
  rTemps <- lapply(rTemps,wrap)
  winds <- list()
  for (meth in tolower(methods)){
    dates = stormextent |> filter(source=="native")|>pull(date)|>unique()
    if (!is.null(todir)){
      tofiles <- paste0(todir,"/",meth,"_",unique(stormextent$ID),"_",unique(format(dates,"%Y%m%d%H%M")),".tif")
      if (any(file.exists(tofiles))&overwrite==FALSE){
        mswexists <- tofiles[file.exists(tofiles)]
        dates <- dates[!file.exists(tofiles)]
      }else{mswexists <- NULL}
    }
    if (length(dates)>0){
      if (meth=="tps"){
        stormextent_model <- stormextent |> filter(date %in% dates)
        ##  can only compute TPS on non-missing wind extents
        ##  the last date will be included on the previous timestep, so remove it
        if (length(dates)>1) dates <- dates[-length(dates)]
        cat(paste0(round(100*length(dates)/(length(stormextent|>filter(location=="track points",source=="native")|>pull(date)|>unique())-1)),"% of original data included in TPS calculation. Adjust t_res for more complete inclusion.\n"))
      } else {
        stormextent_model <- stormextent |> filter(source=="native",location=="track points") |>
          shift_track()
      }
      if (!is.null(todir)){
        newdir <- paste0(todir,"/",meth,"/")
        if (!dir.exists(newdir)) dir.create(newdir)
      }else{newdir=NULL}
      fun <- match.fun(meth)
      cat(paste0("processing wind for ", unique(stormextent$name),"_",unique(format(stormextent$date,"%Y"))," via ",meth,"\n"))
      if (parallel){
        msw <- parallelwind(dates, stormextent_model, rTemps,fun,eye_option=eye_option)
      }else{
        msw <- lapply(seq_along(dates),fun,stormextent_model,rTemps,eye_option=eye_option)
      }
      msw <- c(mswexists,msw)
    }else{
      msw <- mswexists
    }
    cat("\n")
    msw <- Filter(Negate(is.null), msw)
    msw <- unlist(interp_rast(msw,stormextent,parallel))
    msw <- deliver_wind(msw,stormextent,newdir,meth,overwrite,loadrasts,ex_parallel)
    winds=append(winds,list(msw))
    cat("\n")
  }
  names(winds) <- paste(unique(stormextent$ID[!is.na(stormextent$ID)]),"wind",tolower(methods),sep="_")
  return(winds)
}
initiatepar <- function(cpus,type="wind"){
  cat("Parallel = TRUE, initiating parallel workers\n")
  if (is.null(cpus)) {cat(paste0("Number of cpus not specified, alloting 10% of available cores: ", round(0.1*parallel::detectCores())," cores alloted."));cpus = round(0.1*parallel::detectCores())}
  if (cpus>0.1*parallel::detectCores()) cat("Warning: number of input cpus greater than 10% of available cores.\n")
  # Parallel via parallel and pbapply
  # library(parallel)
  # library(pbapply)
  # cl <- makeCluster(cpus)
  # if (type=="wind"){
  #   clusterEvalQ(cl, {
  #     library(dplyr)
  #     library(fields)
  #     library(geosphere)
  #     library(Cyclones)
  #     })
  # }else if (type=="surge"){clusterEvalQ(cl, library(gstat))}
  # cl
  # parallel via snowfall
  ####################
  library(snowfall)
  sfStop()
  #logtmp <- tempfile(fileext=".txt")
  sfInit(parallel=TRUE, cpus)
  suppressMessages({
    sfLibrary(dplyr)
    sfLibrary(sf)
    sfLibrary(terra)
    sfLibrary(Cyclones)
    if (type=="surge"){sfLibrary(gstat)}
    if (type=="wind"){
      sfLibrary(dplyr)
      sfLibrary(fields) # for the TPS models
      sfLibrary(geosphere)  # for the bearing function
    }
    if (type=="extents"){
      sfLibrary(purrr)
      sfLibrary(tidyr)
      #exp_model_extent <- Cyclones:::model_extent
      #sfExport("exp_model_extent")
      #exp_stdh_cast_substring <- Cyclones:::stdh_cast_substring
      #sfExport("exp_stdh_cast_substring")
      #exp_rot <- Cyclones:::rot
      #sfExport("exp_rot")
    }
    if (type=="precip"){sfLibrary(googledrive);sfLibrary(earthdatalogin)}
  })
  # sfLibrary(snowfall) # for sfCat messaging capability
}
parallelwind <- function(dates,cents, r,meth,eye_option) {
  ##  must wrap the template raster in order to pass to all the nodes
  #msw <- pblapply(seq_along(dates),meth, cents, r,todir,overwrt,cl=cluster)
  #msw <- sfLapply(seq_along(dates),meth, cents, r,todir,overwrt)
  msw <- sfClusterApplyLB(seq_along(dates),meth, cents, r,eye_option=eye_option)
  msw
}
deliver_wind <- function(winds,track,todir,source,overwrite,loadrsts,ex_parallel){
  #tofiles <-paste0(todir,"/tps_",unique(tracks$ID[!is.na(tracks$ID)]),"_",unique(format(d1,"%Y%m%d%H%M")),".tif")
  if (class(winds[[1]])!="character") {
    winds <- lapply(winds, unwrap)
    ###  only keep the files that arent already saved if overwrite is FALSE?
    ### can only do this if out of parallel
    ### for parallel, saving is done once all files are assembled
    tofiles <- paste0(todir,"/",source,"_",unique(track$ID),"_",format(as.POSIXct(unique(unlist(lapply(winds,terra::time)))),"%Y%m%d%H%M",tz="UTC"),".tif")
    if (!is.null(todir)){
      cat(paste0("Saving to: ",todir,".","\n"))
      if (!overwrite){
        cat("Overwrite set to FALSE, existing files will be SKIPPED.\n")
        if (!all(file.exists(tofiles))) {
          winds <- winds[!file.exists(tofiles)]
          tofiles <- tofiles[!file.exists(tofiles)]
          lapply(1:length(winds),function(x) writeRaster(winds[[x]],tofiles[x],overwrite=overwrite))
        }
      }else{
        cat("Overwrite set to TRUE, existing files will be REPLACED.\n")
        lapply(1:length(winds),function(x) writeRaster(winds[[x]],tofiles[x],overwrite=overwrite))
      }
    }
  }else{
   winds <- unlist(winds)
  }
  if (loadrsts|is.null(todir)){
    if (ex_parallel) return(wrap(rast(winds)))
    else(return(rast(winds)))
  }
}
load_wind <- function(storm,todir,loadrasts){
  if (is.null(todir)){
    todir=getwd()
  }
  meths <- list.dirs(paste0(todir,"/",storm,"/"))[-1]
  winds = list.files(paste0(todir,"/",storm,"/"),recursive = TRUE,full.names = TRUE,pattern=".tif")
  if (length(winds)==0) stop("No .tif files found in supplied directory. Do you need to specify the todir?")
  out <- list()
  for (m in meths){
   winds = list.files(m,recursive = TRUE,full.names = TRUE,pattern=".tif")
    if (length(winds)>0){
      if (loadrasts) winds = rast(winds)
      out <- append(out,list(winds))
    }
  }
  names(out) <- basename(meths)
  return(out)#setNames(list(out),paste(strsplit(precips[[1]],"_")[[1]][c(5:8)],collapse ="_")))
}


prep_theoretical_data <- function(L,extents,tmpRas){
  id =unique(extents$ID[!is.na(extents$ID)])
  cent <- extents |> slice(L)
  tmpRasP <- tmpRas$rTempP
  tmpRas <- tmpRas$rTempG
  if (class(tmpRas)[1]=="PackedSpatRaster"){tmpRas=suppressWarnings(rast(unwrap(tmpRas)));tmpRasP=suppressWarnings(rast(unwrap(tmpRasP)))}
  #tmpRas <- crop(tmpRas,ext(extents))
  msw = cent$maxwind.ms
  rmw <- cent$rmw.m/1000
  maxpress= cent$maxpress.mb/0.01
  minpress=cent$minpress.mb/0.01
  deltP <- maxpress - minpress
  if (!is.na(deltP)&&deltP==0) deltP=1
  crds <- terra::crds(tmpRas, na.rm = FALSE)
  x <- crds[, 1] - cent$centerX_shifted_geo
  y <- crds[, 2] - cent$centerY_shifted_geo
  # Computing distances to the eye of the storm in m
  distEye <- terra::distance(
    x = crds,
    y = st_coordinates(cent|>st_transform(4326)|>st_shift_longitude()),
    lonlat = TRUE
  )* 0.001
  list(vr=distEye,cent=cent,rmw=rmw,msw=msw,deltP=deltP,minpress=minpress,tmpRas=tmpRas,x=x,y=y,crds=crds)
}


package_theoretical_data <- function(dat,tmpRas,tmpRasP,dir,meth,smooth=FALSE){
  #direction <- rast(t(matrix(direction,ncol=dim(tmpRas)[1])),crs=crs(tmpRas),extent=ext(tmpRas))
  ##  to get power, must first compute pressure field
  ###  the pressure field should just be a linear interpolation from the center to the roci
  ##  start with the distance to the center
  distr <- rast(matrix(dat$vr,ncol=dim(tmpRas)[1]),crs=crs(tmpRas),extent=ext(tmpRas))
  distr <- resample(distr,tmpRas)
  ##  the pressure shouldnt increase after the roci, so set all values greater than roci to roci
  distr[distr>(dat$cent$roci.m/1000)] <- dat$cent$roci.m/1000
  P <- dat$minpress+(distr/0.001)*(dat$deltP/(dat$cent$roci.m))
  dens <- P*100/(287.058*298)
  kW <- as.numeric(dat$cent$dt)*(0.5*dens*1*(tmpRas)^3)/1000
  kW[is.na(kW)] <- 0
  terra::units(tmpRas) <- "m/s"
  terra::units(kW) <- "kW"
  terra::units(dir) <- "deg"
  tmpRas <- rast(list(power.kW=kW,msw.ms=tmpRas,windir.deg=dir))
  tmpRas <- mask(tmpRas,st_transform(st_buffer(dat$cent,dat$cent$roci.m),4326)|>st_shift_longitude())
  names( tmpRas) <- paste0(meth,"_",names(tmpRas))
  terra::time(tmpRas) <- rep(dat$cent$date,each=3)
  if (smooth){
    tmpRas <- stormRsmooth(tmpRas,s_res,unwrap(tmpRasP))
  }else{
    tmpRas <- project(tmpRas,unwrap(tmpRasP))
  }
  return(wrap(tmpRas))
}

check_extents <- function(exnt,meths,s_res){
  if (!any(grep(c("TPS|Willoughby|Boose|Holland"), meths,ignore.case=TRUE))) stop("Unkown 'methods' input")
  options(warn=1)
  if (any(grep(c("Boose|Holland"), meths,ignore.case=TRUE))&(all(is.na(exnt$minpress.mb))||all(is.na(exnt$maxpress.mb)))){
    meths <- meths[-grep(c("Boose|Holland"), meths,ignore.case=TRUE)]
    warning("Either all of the minimum or maximum pressure values are missing, cannot compute Boose or Holland methods. Use models in 'make_extents()' to model missing values or choose another method.")
    if (length(meths)==0) return(NULL)
  }
  if (any(grepl("TPS", meths,ignore.case=TRUE))){
    if (all(is.na(exnt$kts))||all(exnt$kts==0)||nrow(exnt |> filter((!is.na(kts)|kts>0),!is.na(roci.m)))==0){
      meths <- meths[-grep("TPS",meths,ignore.case=TRUE)]
      warning("No complete wind field extents found in input. TPS requires at least some wind extents. Use models in 'make_extents()' to model missing values.")
    }

    if (nrow(exnt |> filter((!is.na(kts)|kts>0),!is.na(roci.m)))<length(unique(exnt$date))) warning("Not all dates have wind extents. TPS will only be calculated for dates with wind extents.")
    if (all(is.na(exnt$minpress.mb))|all(is.na(exnt$maxpress.mb))) warning("Either all of the minimum or maximum pressure values are missing, cannot compute pressure difference for TPS power calculation. Power will be missing. Use models in 'make_extents()' to model missing values")
  }
  tempextent <- exnt |> group_by(date)|>mutate(missingROCI= !("ROCI" %in% location))
  if (any(tempextent|>pull(missingROCI))){
    ###  some dates dont have a ROCI extent but they do have an interpolated ROCI value
    ###  use that if available
    ### otherwise, use an average across all storms (~345 km)
    missingextent <- tempextent |>
      filter(missingROCI)|>
      group_by(date)|>
      mutate(roci.m=if_else(all(is.na(roci.m)),400000,unique(roci.m)))
    if (any(missingextent$roci.m==400000)) warning("Radius of Last Closed Isobar Missing in some time steps. Using all storms mean value of 345 km + 55 km for storm extent.")
    missingroci <- missingextent|>
      filter(location=="track points")
    missingroci <- st_buffer(missingroci,missingroci$roci.m)|>
      mutate(location="ROCI avg.")|>
      st_cast("LINESTRING")
    extent <-bind_rows(tempextent|>filter(!missingROCI),
                       missingextent,
                       missingroci)|>
      select(-missingROCI)|>
      ungroup() |>
      arrange(date)
    rTempP <- rast(ext=extent |> ext(), resolution=s_res,
                   crs=crs(extent))
  }else{
    rTempP <- rast(ext=exnt |> ext(), resolution=s_res,
                   crs=crs(exnt))
    extent <- exnt
  }

  list(stormextent=extent,rTempP=rTempP,meths=meths)
}
