#' Generate 2D wind fields for a storm
#'
#'`get_wind()` will accept the output of 'make_extents()' and return a series of raster stacks, one for each time step, representing the desired wind related variables. The temporal resolution of the rasters will be the same as that
#' of the input wind extents.
#'
#' @param stormextent A set of storm wind extents generated by the 'make_extents()' function. If not used with an apply function, only the first storm will be processed.
#' @param s_res The spatial resolution, in meters, of the desired output. Higher resolutions (lower numbers) will take significantly longer and parallel processing may be warranted below
#' 10000 meters.
#' @param methods One or all of 'tps', 'boose', 'willoughby', or 'holland'. See details below. 'all' will perform all of the methods.
#' @param cpus How many cpu cores to assign for parallel processing. Recommended to verify available cores before using.
#' @param todir The target directory for final rasters. If not provided, rasters will be loaded in memory. Thus, highly recommended for high resolution products or for batch processing.
#' @param overwrite Should existing files in 'todir' be overwritten. If not, those will be skipped.
#' @param smooth Should a smoothing function be applied, analagous to that applied to StormR products.
#' @param eye_option How the eye wall is processed when creating rasters. See details.
#' @returns Raster stacks, one for each time step in the output of 'make_extents()', with the spatial resolution of 's_res' and the spatial extent of the cumulative radius of the last
#' closed isobar (ROCI), representing the maximum sustained wind in meters per second, the wind direction in degrees, and the total power in kilowatts exerted by the maximum sustained
#' wind on 1 square meter of a surface for the duration of the time step.
#' @details Maximum sustained wind is defined differently across agencies and methods, but is generally summarised as the average wind speed sustained over a given period of time, the interval.
#' Intervals vary by agency, with 10-minutes being the most common and with USA agencies utilizing 1-minute intervals. In cyclones, wind speeds are highest towards the center and decrease
#' non-linearly as a function of the distance from the center. Several theoretical models have been proposed to generalize this relationship and can be utilized in 'get_wind()'. These functions
#' utilize the storm's location and its maximum wind speed and pressure differential to predict wind speeds anywhere within the footprint.
#' [Holland, 1980]("https://doi.org/10.1175/1520-0493(1980)108<1212:AAMOTW>2.0.CO;2") describes this as a function of the pressure field and the radius of maximum wind.
#' [Boose, 2004]("https://harvardforest.fas.harvard.edu/publications/pdfs/Boose_Chapter_HurricanesTyphoons_2004.pdf") expands upon this, introducing asymmetry and differential interactions
#' over land and water. [Willoughby, 2006]("https://doi.org/10.1175/MWR3106.1") is a piecewise function that stitches together two models, one for the inner region of the storm and another for
#' the outer region. The algorithms for these methods were adapted from the StormR package. Finally, an interpolation method, Thin Plate Spline, can be applied to the extents constructed by
#' 'make_extents()'. Although computationally more demanding, TPS is shown here to best generalize observations from drop sondes.
#' @examples
#' # One storm, coarse resolution, with native extents only and with consolidated values.
#' Helene <- get_storms(name='HELENE',season=2024)
#' Helene_extents <- make_extents(Helene)
#' Helene_winds <- get_wind(Helene_extents,methods='all')
#' Helene_winds <-rast(lapply(Helene_winds,unwrap))
#' Helene_msw <- Helene_winds[[grep("msw",names(Helene_winds))]]
#' plot(Helene_msw[[c(grep("tps",names(Helene_msw))[1],grep("boose",names(Helene_msw))[1],grep("holland",names(Helene_msw))[1],grep("willoughby",names(Helene_msw))[1])]])
#' ##  take the maximum wind speed across the storm's lifetime
#' Helene_msw.max <- tapp(Helene_msw,c(ifelse(grepl("tps",names(Helene_msw)),"tps",ifelse(grepl("boose",names(Helene_msw)),"boose",ifelse(grepl("holland",names(Helene_msw)),"holland","willoughby")))),fun="max",na.rm=TRUE)
#' plot(Helene_msw.max)

#' @importFrom sf st_coordinates st_as_sfc st_sf st_crs st_shift_longitude st_geometry_type
#' @importFrom terra rast res ext extend approximate setValues shift resample app allNA ifel time rotate wrap sources crs project
get_wind <- function(stormextent,s_res=20000,methods=NULL,cpus=NULL,
                     todir=NULL,overwrite=FALSE,smooth=FALSE,eye_option="maxwind",loadrasts=TRUE){
  if (!is.null(cpus)){parallel <- TRUE;on.exit(sfStop())}else{parallel <- FALSE}
  ###  if the supplied input are directories of previously saved rasters, load those
  if (class(stormextent)[1]=="character") return(load_wind(stormextent,todir,loadrasts))
  ###  this must be done before the directory/file check
  ###  if multiple storms are passed to the function,
  if (is.null(dim(stormextent))){
    if (class(stormextent)=="numeric") stop("Unknown data source. Did you use lapply on a single storm?")
    options(warn=1)
    warning("More than one storm in data. Only first will be used. Use lapply or a parallel equivalent to repeat for multiple storms.")
    stormextent <- stormextent[[1]]
    options(warn=0)
  }else{
    if (!"sf" %in% class(stormextent)) error("Input is not a spatial storm extent. Use 'make_extents()' to create storm extent.")
  }
  if (is.null(dim(stormextent))){
    if ("linestrings" %in% names(stormextent)) stormextent <- stormextent$linestrings
    else stormextent <- stdh_cast_substring(stormextent)
  }else if ("POLYGON" %in% unique(st_geometry_type(stormextent))){
    stormextent <- stdh_cast_substring(stormextent)
  }
  ##  if the call to the function was not direct "get_wind()" or wrapped in an lapply for sequential processing, its likely a parallel wrapper has been used
  ##  in this case, further parallelization is not supported
  ##  check for external parallelization
  ex_parallel <- any(unlist(lapply(sys.calls(), function(cal) {
    as.character(cal[[1]]) %in% c("slaveLoop", "%dopar%","workLoop")
  })))
  if (parallel){
    if (ex_parallel) stop("Another wrapper function detected. Is parallel processing already implemented at the storm level? Nested parallel operations  not currently supported.")
    if (!"snowfall" %in% installed.packages()) stop("package 'snowfall' not detected but necessary for internal parallel operations.")
    cl <- initiatepar(cpus)
  }
  if(any(methods=="all")) methods=c("TPS","Willoughby","Boose","Holland")
  if (!any(grep(c("TPS|Willoughby|Boose|Holland"), methods,ignore.case=TRUE))) stop("Unkown 'methods' input")
  options(warn=1)
  if (any(grep(c("Boose|Holland"), methods,ignore.case=TRUE))&(all(is.na(stormextent$minpress.mb))||all(is.na(stormextent$maxpress.mb)))){
    warning("Either all of the minimum or maximum pressure values are missing, cannot compute Boose or Holland methods. Use 'get_storms()' with modelling or choose another method.")
    methods <- methods[-grep(c("Boose|Holland"), methods,ignore.case=TRUE)]
  }
  if (any(grepl("TPS", methods,ignore.case=TRUE))){
    if (all(is.na(stormextent$kts))||all(stormextent$kts==0)||nrow(stormextent |> filter((!is.na(kts)|kts>0),!is.na(roci.m)))==0){
      methods <- methods[-grep("TPS", methods,ignore.case=TRUE)]
      warning("No complete wind field extents found in input. TPS requires at least some wind extents. Use models in 'make_extents()' to model missing values.")
    }
    if (nrow(stormextent |> filter((!is.na(kts)|kts>0),!is.na(roci.m)))<length(unique(stormextent$date))) warning("Not all dates have wind extents. TPS will only be calculated for dates with wind extents.")
    if (all(is.na(stormextent$minpress.mb))||all(is.na(stormextent$maxpress.mb))) warning("Either all of the minimum or maximum pressure values are missing, cannot compute pressure difference for TPS power calculation. Power will be missing. Use 'get_storms()' with modelling.")
  }
  options(warn=0)
  if (!is.null(todir)){
    if (!substr(todir,nchar(todir),nchar(todir))=="/") todir=paste0(todir,"/")
    if (!dir.exists(todir)) stop("Specified todir directory not found.")
    t_res <- difftime(stormextent|>filter(location=="track points")|>pull(date),lead(stormextent|>filter(location=="track points")|>pull(date)),units="mins")|>as.numeric()|>unique()|>abs()|>mean(na.rm=TRUE)
    todir <-  paste0(todir,unique(stormextent$name),unique(format(stormextent$date,"%Y")),"_",s_res,"_",t_res,"_WIND")
    if (!dir.exists(todir)) dir.create(todir)
    if (overwrite==FALSE) cat(paste0("Saving to: ",todir,". Overwrite set to FALSE, existing files will be SKIPPED.","\n"))
    else cat(paste0("Saving to: ",todir,". Overwrite set to TRUE, existing files will be REPLACED.","\n"))
  }
  ####  also create break to aggregate the files if resolution is too high
  ##  create template raster for all methods to project upon
  ##  TPS just needs a projected crs
  ##  must use a shifted(rotated) crs to avoid the antimeridian for theoretical models
  ##  if the ROCI is missing, assume it is around 500km
  if (any(stormextent |> group_by(date)|>mutate(missingROCI= !("ROCI" %in% location))|>pull(missingROCI))){
    warning("ROCI missing for some dates, assuming 500 km for storm extent calculations")
    tempextent <-bind_rows(stormextent |> filter(location=="ROCI"),
                           stormextent |> filter(location=="track points") |> st_buffer(500000))
    rTempP <- rast(ext=tempextent |> ext(), resolution=s_res,
                   crs=crs(tempextent))
  }else{
    rTempP <- rast(ext=stormextent |> ext(), resolution=s_res,
                   crs=crs(stormextent))
  }
  rTemps <- list(rTempG=rotate(project(rTempP,"epsg:4326")),rTempP=rTempP)
  #centers = interp_track(stormextent,t_res,rTemps$rTempG)
  rTemps <- lapply(rTemps,wrap)
  winds <- list()
  for (meth in tolower(methods)){
    if (meth=="tps"){
      ##  can only compute TPS on non-missing wind extents
      dates = stormextent |> filter(!location %in% c("track","track points"))|>pull(date)|>unique()
      ##  the last date will be included on the previous timestep, so remove it
      if (length(dates)>1) dates <- dates[-length(dates)]
      cat(paste0(round(100*length(dates)/length(unique(stormextent$date))),"% of original data included in TPS calculation. Adjust t_res for more complete inclusion.\n"))
    } else {
      dates=stormextent |> filter(location=="track points")|>pull(date)|>unique()
    }
    if (!is.null(todir)){
      newdir <- paste0(todir,"/",meth,"/")
      if (!dir.exists(newdir)) dir.create(newdir)
    }else{newdir=NULL}
    fun <- match.fun(meth)
    cat(paste0("processing wind for ", unique(stormextent$name),"_",unique(format(stormextent$date,"%Y"))," via ",meth,"\n"))
    if (parallel){
      msw <- parallelwind(dates, stormextent, rTemps,cpus,fun,newdir,overwrite,cl)
    }else{
      msw <- lapply(seq_along(dates),fun,stormextent,rTemps,newdir,overwrite,eye_option=eye_option)
    }
    msw <- Filter(Negate(is.null), msw)

    msw <- deliver_wind(msw,stormextent,newdir,meth,overwrite,loadrasts,ex_parallel)
    winds=append(winds,list(msw))
    cat("\n")
  }
  names(winds) <- paste(unique(stormextent$ID[!is.na(stormextent$ID)]),"wind",tolower(methods),sep="_")
  return(winds)
}
initiatepar <- function(cpus,type="wind"){
  cat("Parallel = TRUE, initiating parallel workers\n")
  if (is.null(cpus)) {cat(paste0("Number of cpus not specified, alloting 10% of available cores: ", round(0.1*parallel::detectCores())," cores alloted."));cpus = round(0.1*parallel::detectCores())}
  if (cpus>0.1*parallel::detectCores()) cat("Warning: number of input cpus greater than 10% of available cores.\n")
  # Parallel via parallel and pbapply
  # library(parallel)
  # library(pbapply)
  # cl <- makeCluster(cpus)
  # if (type=="wind"){
  #   clusterEvalQ(cl, {
  #     library(dplyr)
  #     library(fields)
  #     library(geosphere)
  #     library(Cyclones)
  #     })
  # }else if (type=="surge"){clusterEvalQ(cl, library(gstat))}
  # cl
  # parallel via snowfall
  ####################
  library(snowfall)
  sfStop()
  #logtmp <- tempfile(fileext=".txt")
  sfInit(parallel=TRUE, cpus) ## WARNING: Do not overdo the number of CPUs. Verify your machine's capacity beforehand.
  sfLibrary(sf)
  sfLibrary(terra)
  sfLibrary(Cyclones)
  if (type=="surge"){sfLibrary(gstat)}
  if (type=="wind"){
    sfLibrary(dplyr)
    sfLibrary(fields) # for the TPS models
    sfLibrary(geosphere)  # for the bearing function
    sfLibrary(Cyclones)
  }
  if (type=="extents"){
    sfLibrary(dplyr)
    sfLibrary(purrr)
    sfLibrary(tidyr)
    #exp_model_extent <- Cyclones:::model_extent
    #sfExport("exp_model_extent")
    #exp_stdh_cast_substring <- Cyclones:::stdh_cast_substring
    #sfExport("exp_stdh_cast_substring")
    #exp_rot <- Cyclones:::rot
    #sfExport("exp_rot")
  }
  if (type=="precip"){sfLibrary(googledrive);sfLibrary(earthdatalogin)}
  # sfLibrary(snowfall) # for sfCat messaging capability
}
parallelwind <- function(dates,cents, r,cpus,meth,todir=NULL,overwrt,cluster) {
  ##  must wrap the template raster in order to pass to all the nodes
  #msw <- pblapply(seq_along(dates),meth, cents, r,todir,overwrt,cl=cluster)
  #msw <- sfLapply(seq_along(dates),meth, cents, r,todir,overwrt)
  msw <- sfClusterApplyLB(seq_along(dates),meth, cents, r,todir,overwrt)
  lapply(msw,unwrap)
}
deliver_wind <- function(winds,track,todir,source,overwrite,loadrsts,ex_parallel){
  #tofiles <-paste0(todir,"/tps_",unique(tracks$ID[!is.na(tracks$ID)]),"_",unique(format(d1,"%Y%m%d%H%M")),".tif")
  tofiles <- paste0(todir,"/",source,"_",unique(track$ID),"_",format(time(rast(lapply(winds,unwrap))),"%Y%m%d%H%M"),".tif")
  ###  only keep the files that arent already saved if overwrite is FALSE?
  ### can only do this if out of parallel
  ### for parallel, saving is done once all files are assembled
  browser()
  if (!is.null(todir)){
    if (!overwrite){
      if (!all(file.exists(tofiles))) {
        winds <- unwrap(winds)[[!file.exists(tofiles)]]
        writeRaster(winds,tofiles[!file.exists(tofiles)],overwrite=overwrite)
      }
    }else{
      writeRaster(unwrap(winds),tofiles,overwrite=overwrite)
    }
  }
  if (loadrsts|is.null(todir)){
    if (ex_parallel) return(lapply(winds,wrap))
    else(return(winds))
  }
}
load_wind <- function(storm,todir,loadrasts){
  if (is.null(todir)){
    todir=getwd()
  }
  meths <- list.dirs(paste0(todir,"/",storm,"_WIND/"))[-1]
  winds = list.files(paste0(todir,"/",storm,"_WIND/"),recursive = TRUE,full.names = TRUE,pattern=".tif")
  if (length(winds)==0) stop("No .tif files found in supplied directory. Do you need to specify the todir?")
  out <- list()
  for (m in meths){
   winds = list.files(m,recursive = TRUE,full.names = TRUE,pattern=".tif")
    if (length(winds)>0){
      if (loadrasts) winds = rast(winds)
      out <- append(out,list(winds))
    }
  }
  names(out) <- basename(meths)
  return(out)#setNames(list(out),paste(strsplit(precips[[1]],"_")[[1]][c(5:8)],collapse ="_")))
}

