#' Generate 2D precipitation fields for a given storm
#'
#'`get_precip()` will accept the output of either 'get_storms()' or 'make_extents()' and return a series of raster stacks, representing the total precipitation
#' accumulation for each time step. The temporal resolution of the rasters will be the same as that of the input data, unless otherwise specified. For all sources, some sort of
#' pre-registration for each source, and subsequent configuration in R is necessary to access data. See details. Additional packages are also necessary for API interaction at each source.
#' These will be prompted for when required. Alternatively, data could be downloaded manually and held in the './~dpath~/source/' directory, ensuring original filenames are retained,
#' for loading via 'get_precip()'.
#'
#' @param storm A set of storm tabular data generated by 'get_storms()' or wind extents generated by 'make_extents()'. If not used with an apply function, only the first storm will be processed.
#' @param sources Where to source the precipitation data, one or all of "ecmwf","mswep",or "gpm". "all" will return all. See details.
#' @param dpath The download path of the sourced precipitation data. Raw files will be stored here and then searched for here before downloading from the web. In some cases, these are global
#' files, meaning they can be used for any storm sharing the same date(s). For 'ecmwf' the files are cropped to storm extents before downloading and are this storm-specific.
#' Recommended for batch and repetitive analyses.
#' @param todir The target directory for final storm rasters. If not provided, rasters will be loaded in memory. Thus, highly recommended for high resolution products or for batch processing.
#' @param s_res The spatial resolution, in meters, of the desired output. Higher resolutions (lower numbers) will take significantly longer and parallel processing may be warranted below
#' 10000 meters.
#' @param t_res The temporal resolution, in minutes, of the desired output. If not provided, the resolution of the source dataset will be used. If provided and different from the source data,
#' results will be interpolated to meet the desired resolution.
#' @param pre Numeric integer for the number of days of pre-storm precipitation to inlcude, as pre-cyclone precipitation events are acknowledged to sometimes heavily influence
#' soil moisture, surface flow, and storm-water dynamics during and after the storm.
#' @param cpus How many cpu cores to assign for parallel processing. Recommended to verify available cores before using.
#' @param overwrite Should existing files in 'todir' be overwritten. If not, those will be skipped.
#' @details It is generally accepted that 95% of cyclone sourced precipitation falls within 500km of the center [Guzman & Jiang, 2012]("https://www.nature.com/articles/s41467-021-25685-2"),
#' [Chen et al. (2024)]("https://doi.org/10.1175%2FJCLI-D-23-0666.1) (Future versions of this function will attempt to make the 500km distance variable). Under this premise,
#' precipitation datasets are subset by buffering a 500km radius around the storm's center at
#' each interval. Although time conventions differ by source, the product of 'get_precip()' will always reflect the end time for each interval, not the start time. "ecmwf" is default and is the
#' [European Center for Medium-Range Weather Forecasts ERA5 dataset]("https://www.ecmwf.int/en/forecasts/dataset/ecmwf-reanalysis-v5"), which has global coverage from 1940 to present
#' at hourly intervals and ~30 km spatial resolution. [Register for ECMWF here.]("https://www.ecmwf.int/user/login) "mswep" is the
#' [Multi-Source Weighted-Ensemble Precipitation product]("https://www.gloh2o.org/") (V2) from GloH2O, which has global coverage from 1979 to present at 3-hourly intervals and 0.1 degree (10 km)
#' spatial resolution. These are housed in Google Drive and whichever account is used to request access to the data must also be the one used with 'googledrive::drive_auth()'.
#' Googleapis (the backend of the googledrive package) will sometimes block requests and downloads will fail. You may need to specifically clear the authorization cache and
#' re-grant Tidyverse API access to your account via 'unlink("~/.R/gargle/gargle-oauth")' and then 'googldrive::drive_auth(cache=FALSE)'. Otherwise, Google Drive does
#' implement throttling when download quotas are exceeded per file, regardless of who is requesting the file. In this case waiting is the only resolution. "gpm" is data from the
#' [National Aeronautics and Space Administration's Global Precipitation Mission]("https://gpm.nasa.gov/missions/GPM"), specifically the IMERG product, which is global coverage 30-minute interval
#' data from 2000 to the present. [Register first here]("https://urs.earthdata.nasa.gov/") and obtain a token, which then needs to be configured to R via 'earthdatalogin::edl_set_token()'.
#' Although MSWEP has the highest resolution and seems to be robust, it is proprietary and may eventually be inaccessible. Although the GPM data share the same
#' high resolution as MSWEP, the maximum values are much higher than the other sources and this overestimation [has been noted]("https://journals.ametsoc.org/view/journals/hydr/24/10/JHM-D-22-0216.1.xml").
#' Thus, ecmwf is used by default.
#' @examples
#' # One storm, coarse resolution, at native ~3hr intervals, all sources.
#' # first run will be relatively slow as data is acquired
#' # subsequent runs are much faster when 'dpath' is utilized or in the same R session
#' Helene <- get_storms(name='HELENE',season=2024)
#' Helene_extents <- make_extents(Helene)
#' Helene_precips <- get_precip(Helene_extents,sources='all',prestorm=TRUE)
#' ##  precips separated into storm and pre-storm (if indicated) periods
#' Helene_prestorm_precips <- lapply(Helene_precips,function(x) x$prestorm)
#' Helene_precips <- lapply(Helene_precips,function(x) x$storm)
#' ## original layer names retained within storm stacks
#' Helene_precips <-lapply(Helene_precips, function (x) unwrap(x))
#' Helene_prestorm_precips <-lapply(Helene_prestorm_precips, function (x) lapply(x,unwrap))
#' ###  plot the same date across the different sources
#' plot(c(Helene_precips$HELENE_2024_NA_2024268N17278_precip_ecmwf[[50]],Helene_precips$HELENE_2024_NA_2024268N17278_precip_gpm[[50]],Helene_precips$HELENE_2024_NA_2024268N17278_precip_mswep[[50]]))
#' time(c(Helene_precips$HELENE_2024_NA_2024268N17278_precip_ecmwf[[50]],Helene_precips$HELENE_2024_NA_2024268N17278_precip_gpm[[50]],Helene_precips$HELENE_2024_NA_2024268N17278_precip_mswep[[50]]))
#' ##  plot a date and all cells that fall within 48 hours before that time
#' Helene_t1 <- Helene_precips$HELENE_2024_NA_2024268N17278_precip_ecmwf[[50]]
#' time(Helene_t1)
#' Helene_t1_pre48hrs <- Helene_prestorm_precips$HELENE_2024_NA_2024268N17278_precip_ecmwf$prestorm_precip_48_hrs[[time(Helene_prestorm_precips$HELENE_2024_NA_2024268N17278_precip_ecmwf$prestorm_precip_48_hrs)==time(Helene_t1)-48*60*60]]
#' Helene_t1_minus48hrs <- Helene_precips$HELENE_2024_NA_2024268N17278_precip_ecmwf[[time(Helene_precips$HELENE_2024_NA_2024268N17278_precip_ecmwf)==time(Helene_precips$HELENE_2024_NA_2024268N17278_precip_ecmwf[[50]])-48*60*60]]
#' plot(c(Helene_t1,Helene_t1_pre48hrs, Helene_t1_minus48hrs))
#' ##  take the sum of the precipitation across the storm's lifetime
#' Helene_precips.sum <- tapp(rast(Helene_precips),sapply(strsplit(names(rast(Helene_precips)),"_"),"[[",6),fun="sum",na.rm=TRUE)
#' plot(Helene_precips.sum,range=c(0,450))
#' ## prestorm sum
#' Helene_prestorm48hrs.sum <- app(Helene_prestorm_precips$HELENE_2024_NA_2024268N17278_precip_ecmwf$prestorm_precip_48_hrs,fun="sum",na.rm=TRUE)
#' plot(Helene_prestorm48hrs.sum)
#' ##  North Carolina received considerable pre-storm precipitation
#' plot(st_geometry(st_transform(rnaturalearth::ne_states(),crs(Helene_prestorm48hrs.sum))),add=TRUE,border="grey")
#'
#' ##  high resolution in parallel
#' Helene_precips <- get_precip(Helene_extents,sources='all',cpus=10,s_res=5000,t_res=15)
#' @importFrom sf st_as_sf st_transform st_buffer st_bbox
#' @importFrom dplyr filter arrange
#' @importFrom terra writeRaster
get_precip <- function(storm,sources="ecmwf",todir=NULL,dpath=NULL,t_res=NULL,s_res=NULL,prestorm=NULL,
                       agg=FALSE,cpus=NULL,overwrite=FALSE,loadrasts=FALSE){
  ###  if the supplied input are directories of previously saved rasters, load those
  if (class(storm)[1]=="character"){ return(load_precip(storm,todir,loadrasts))
  #############
  ###  checks and initiate variables
  ###########
  ##  check for internal parallelization
  parallel <- !is.null(cpus)
  ##  check for external parallelization
  ex_parallel <- any(unlist(lapply(sys.calls(), function(cal) {
    as.character(cal[[1]]) %in% c("slaveLoop", "%dopar%","workLoop")
  })))
  ##  if the call to the function was not direct "get_wind()" or wrapped in an lapply for sequential processing, its likely a parallel wrapper has been used
  ##  in this case, further parallelization is not supported
  if (parallel){
    if (ex_parallel) stop("Another wrapper function detected. Is parallel processing already implemented at the storm level? Nested parallel operations not currently supported.")
    if (!"snowfall" %in% installed.packages()) stop("package 'snowfall' not detected but necessary for internal parallel operations.")
  }
  if (length(prestorm)==1&is.logical(prestorm)&&prestorm) prestorm=48
  else if(!is.null(prestorm)&&!all(is.numeric(prestorm))) stop("pre storm hours format must be either TRUE or numeric for number of hours before storm.")
  else if(any(prestorm/24 > 7)) warning("pre storm hours exceeds 7 days, expect long data download period.")

  }else if (class(storm)[1]%in% c("vctrs_list_of","list","tbl_df","sf")){
    ###  this must be done before the directory/file check
    ###  if multiple storms are passed to the function,
    if (is.null(dim(storm))){
      #if (!class(storm)[1]=="vctrs_list_of") stop("Unknown data source. Did you use lapply on a single storm?")
      options(warn=1)
      warning("More than one storm in data. Only first will be used. Use lapply or a parallel equivalent to repeat for multiple storms.")
      storm <- storm[[1]]
      options(warn=0)
    }
    ### if the wind extents are supplied
    if ("geometry" %in% names(storm)){
      lines <- storm |>
        group_by(date) |>
        mutate(dt=difftime(lead(date),date,unit="hours"))
    ##  if the tabular data is supplied
    }else{
      ###  create the tracks and track points from the tabular data
      storm$LAT <- as.numeric(storm$LAT);storm$LON=as.numeric(storm$LON)
      custCRSall <- paste0("+proj=lcc +lat_0=",round(mean(storm$LAT,na.rm=TRUE))," +lon_0=",round(mean(storm$LON,na.rm=TRUE))," +lat_1=",ceiling((max(storm$LAT,na.rm=TRUE)-min(storm$LAT,na.rm=TRUE))/6),
                           " +lat_2=",ceiling(5*(max(storm$LAT,na.rm=TRUE)-min(storm$LAT,na.rm=TRUE))/6)," +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs +type=crs")
      points=storm |> st_as_sf(coords=c("LON","LAT"),crs=4326,remove=FALSE)|>
        mutate(quad="track points")
      tr <- points  |>
        mutate(geometry_lead = lead(geometry, default = NULL)) |>
        # drop the NA row created by lagging
        slice(-n()) |>
        mutate(line = st_sfc(purrr::map2(
          .x = geometry,
          .y = geometry_lead,
          .f = ~{st_union(c(.x, .y)) |> suppressWarnings(st_cast("LINESTRING"))}
        ))) |>
        st_drop_geometry()|>
        select(-geometry_lead) |>
        rename(geometry="line")|>
        st_set_geometry("geometry")|>
        st_set_crs(4326)|>
        st_transform(custCRSall)|>
        st_cast("LINESTRING") |>
        mutate(location="track",dist.m=0,dist.m=0,source="native",name=NAME,date=as.POSIXct(ISO_TIME,tz="UTC"),dt=difftime(lead(date),date,unit="hours"),centerX=LON,centerY=LAT)|>
        select(location,dist.m,source,ID,name,date,dt,centerX,centerY)
      point <- st_transform(points,custCRSall) |>
        mutate(location="track points",dist.m=0,source="native",name=NAME,date=as.POSIXct(ISO_TIME,tz="UTC"),dt=difftime(lead(date),date,unit="hours"),centerX=LON,centerY=LAT)|>
        select(location,dist.m,source,ID,name,date,dt,centerX,centerY)
      ###  95% of storm precipitation falls within 500km
      lines <- bind_rows(tr,point,point |> st_buffer(500000,nQuadSegs=2)|> summarise(location="bounds",name=unique(storm$NAME),ID=unique(storm$ID),date=mean(date,na.rm=TRUE),dt=mean(dt,na.rm=TRUE))) |>
        arrange(date)
    }
  }else{
    stop("unknown data source for 'storm'")
  }

  if (!is.null(dpath)){
    if (substr(dpath,nchar(dpath),nchar(dpath))!="/") dpath=paste0(dpath,"/")
    if (!dir.exists(dpath)) stop("Specified 'dpath' directory not found.")
    if (!grepl("precip|rain",dpath,ignore.case = TRUE)){dpath <- paste0(dpath,"Precipitation/");dir.create(dpath)}

  }else{
    dpath=paste0(tempdir(),"/")
  }
  if (!is.null(todir)){
    if (!substr(todir,nchar(todir),nchar(todir))=="/") todir=paste0(todir,"/")
    if (!dir.exists(todir)) stop("Specified todir directory not found.")
  }
  if(any(sources=="all")) sources=c("ecmwf","gpm","mswep")
  if (!any(grep(c("ecmwf|gpm|mswep"), sources,ignore.case=TRUE))) stop("Unkown 'source' input")
  if ("mswep" %in% sources){
    if (!require("googledrive")) error("'googledrive' package necessary for 'mswep' data downloads. Please install it and run 'googledrive::drive_auth()' to authenticate.")
    if (is.null(googledrive::drive_user())) stop("googledrive not yet authorized. Use 'googledrive::drive_auth()' to login to your google account and authorize.")
  }
  if ("ecmwf" %in% sources){
    if (!require("ecmwfr")) error("'ecmwfr' package necessary for 'ecmwfr' data downloads. Please install it and run 'ecmwfr::wf_set_key()' with your token to authenticate.")
    if (is.null(ecmwfr::wf_get_key())) stop("No ecmwf key detected. Register at 'ecmwf.int/user/login' and use ecmwfr::wf_set_key() to set your given key.")
  }
  if("gpm" %in% sources){
    if (!require("earthdatalogin")) error("'earthdatalogin' package necessary for 'gpm' data downloads. Please install it.")
  }
  precips <- list()
  for (source in tolower(sources)){
    returnNULL <- FALSE
    sres <- s_res
    ###  set the native resolutions if not applied
    if (source=="mswep"){
      if (any(unique(as.numeric(storm$SEASON))<1979)){options(warn = 1);warning("MSWEP not available pre 1979, returning NULL");options(warn = 0);returnNULL=TRUE}
       #dates <- seq.POSIXt(min(lines$date,na.rm=TRUE),max(lines$date,na.rm=TRUE),by=180*60)
      if (is.null(t_res)) t_res=180
      #if(t_res!=180) interpt=TRUE
      if (is.null(sres)) sres=10000
      #if (s_res<10000) warning("'s_res' is less than the native resolution (10000 m). Results will lose accuracy.")
    }else if (source =="ecmwf"){
      if (is.null(t_res)) t_res=60
      #if(t_res!=60) interpt=TRUE
      if (is.null(sres)) sres=25000
    }else{
      if (any(unique(as.numeric(storm$SEASON))<1998)){options(warn = 1);warning("GPM not available pre 1998, returning NULL");options(warn = 0);returnNULL=TRUE}
      if (is.null(t_res)) t_res=60
      #if(t_res!=60) interpt=TRUE
      if (is.null(sres)) sres=5000
    }
    dpath_source <- paste0(dpath,source,"/")
    if (!dir.exists(dpath_source)&&!returnNULL){
      dir.create(dpath_source)
      cat(paste0("Source data downloading to / loading from: ",dpath_source,". \n"))
    }
    rTempP <- rast(ext=lines |> ext(), resolution=sres,
                   crs=crs(lines))
    rTemps <- list(rTempG=rotate(project(rTempP,"epsg:4326")),rTempP=rTempP)
    centers = interp_track(lines |> filter(location=="track"),t_res,prestorm,wind=FALSE)|>
      mutate(dt=difftime(lead(date),date,units="hours"),
             maxdate=max(date,na.rm=TRUE),
             minstormdate=min(date[!is.na(source)],na.rm=TRUE))|>
      fill(ID,name,.direction ="downup")
    if (!is.null(todir)){
      newdir <- paste0(todir,unique(lines$name),unique(format(lines$date,"%Y")),"_",sres,"_",t_res,"_PRECIP/")
      if (!dir.exists(newdir)) dir.create(newdir)
      newdir <-  paste0(newdir,source)
      if (!dir.exists(newdir)) dir.create(newdir)
      if (overwrite==FALSE) cat(paste0("Saving to: ",newdir,". Overwrite set to FALSE, existing files will be SKIPPED.","\n"))
      else cat(paste0("Saving processed images to: ",newdir,". Overwrite set to TRUE, existing files will be REPLACED.","\n"))
      if (!dir.exists(newdir)) dir.create(newdir)
    }else{ newdir=NULL}
    cat(paste0("processing precip for ", unique(lines$name),"_",unique(format(lines$date,"%Y"))," via ",source,"\n"))
    if (returnNULL){
      precip=NULL
    }else{
      if (parallel){
        precip <- parallelprecip(centers,source,rTempP,dpath_source,prestorm,cpus)
      }else{
        precip <-  unwrap(do_precip(centers,source,rTempP,dpath_source,prestorm))#do.call(fun,list(centers,rTempP,newdir,dpath,overwrite))
      }
    }
    precip <- deliver_precip(precip,centers,prestorm,newdir,source,overwrite,loadrasts,cpus,ex_parallel)
    precips=append(precips,list(precip))
    cat("\n")
  }
  names(precips) <- paste(unique(centers$ID[!is.na(centers$ID)]),"precip",tolower(sources),sep="_")
  precips
}
parallelprecip <- function(cents,source,r,dpath=NULL,pre_storm,cpus) {
  on.exit(sfStop())
  ##  must wrap the template raster in order to pass to all the nodes
  r <- wrap(r)
  ##  before dividing the storm, get the ID and the already downloaded files in the download dir
  ###  because the list.files is recursive (because each parallel worker creates its own tempdir) it can take a while
  dfiles <- list.files(dpath,recursive=TRUE,pattern="precip_ecmwf_",full.names=TRUE);  dfiles <- dfiles[grep(unique(cents$ID[!is.na(cents$ID)]),dfiles)]
  ##  divide the storm dates. Will also add in the first native date from the next time step for interpolation
  ###  by day
  #cents_div <- split(cents|>filter(date>=min(date[!is.na(ID)])),format(cents|>filter(date>=min(date[!is.na(ID)]))|>pull(date),"%j"))# lapply(split(cents,format(cents$date,"%j")),function(x) bind_rows(x,cents[cents$quad=="bounds",]|>mutate(date=NA)))
  ##  by multiple of cpus
  ##  ensuring there is a multiple of the datasource timestep at each end, to ensure proper interpolation
  ##  ecmwf is hourly but is acquired by day, mswep is three-hourly, gpm is hourly
  if (source=="ecmwf") native <-  format(cents$date,"%M")=="00" else if (source=="gpm") native <- format(cents$date,"%M")%in% c("00","30")  else native <- format(cents$date,"%H:%M") %in% paste0(sprintf("%02d",seq(0,24,by=3)),":00")
  cents <- cents |> mutate(native=native)
  cents_storm <- cents|>filter(date>=unique(minstormdate)) ## |>filter(date>=min(date[!is.na(ID)]))
  ## -1 cpus because we need the other for the predates
  splits <- split(which(cents_storm$native),cut(which(cents_storm$native),cpus-1))
  cents_div <- lapply(1:(length(splits)-1),function(x){cents_storm[c(min(splits[[x]]):splits[[x+1]][1]),]})
  cents_div <- append(cents_div,list(cents_storm[min(splits[[length(splits)]]):nrow(cents_storm),]))
  ##  now add in the prestorm dates
  cents_div <- append(cents_div,list(cents|>filter(date<unique(minstormdate))),after=0)
  ###  the ecmwf requests cannot be made in parallel outside of the wf_request_batch, so that must be done separately
  ###  in that case, only the reprojection is done on parallel cpus
  if (source=="ecmwf"){
    ### dont do one at a time, call get_ecmwf on everything first, including prestorm. Will redirect to wf_request_batch
    precips <- get_ecmwf(cents,dfiles,dpath)
  } else if (source %in% c("mswep","gpm")){
    ##  first download out of parallel?
    precips <- do.call(match.fun(paste0("get_",source)),list(cents,dpath))
  }else{ stop("unknown function call in 'parallelprecip'")}
  precips <- lapply(seq_along(cents_div),function(x,c,r) {
    if (x<length(cents_div)) list(precips=wrap(r[[terra::time(r)<=min(c[[x+1]]$date,na.rm=TRUE)&terra::time(r)>=min(c[[x]]$date,na.rm=TRUE)]]),precips2=NULL,cent=c[[x]])
    else list(precips=wrap(r[[terra::time(r)>=min(c[[x]]$date,na.rm=TRUE)]]),precips2=NULL,cent=c[[x]])
  },c=cents_div,r=unwrap(precips))
  initiatepar(cpus)
  precip <- sfClusterApplyLB(precips,do_precip,source,r,dpath,pre_storm)
  # if (lrsts){
  #   precip_storm= rast(lapply(precip,function(x) unwrap(x$storm)))
  #   precip_prestorm= rast(lapply(precip,function(x) unwrap(x$prestorm)))
  #   if (!is.null(pre_storm)){
  #     precip <- list(storm=wrap(precip_storm),prestorm=pre_sub_precips(precip_prestorm,cents,pre_storm,prll=TRUE))
  #   }else{
  #     precip <- list(storm=wrap(precip_storm))
  #   }
  #   return(rast(lapply(precip,unwrap)))
  # }else{
  #   return(unique(unlist(precip)))
  # }
  precip <- rast(lapply(precip,unwrap))
  precip <- precip[[order(terra::time(precip))]]
  precip
}

#' internal Cyclones function, called by get_precip to route function calls for different data sources and to format final product
#'
#' 'do_precip()' is currently only called by the 'get_precip()' function and its parallel helper 'parallelprecip()'. The function routes processing to the
#' appropriate data acquisition function depending on the desired data source, then applies the same set of routines to ensure all products are formatted consistently.
do_precip <- function(cent,source,r,dpath=NULL,pre_storm){
  ###  if called without parallel
  if (class(cent)[1]=="sf"){
    prll=FALSE
    fun <- match.fun(paste0("get_",source))
    precips <- unwrap(do.call(fun, list(cent,dpath=dpath)))
    precips2 <- NULL
    ##  if called inside parallel
  }else{
    prll=TRUE
    precips <- unwrap(cent$precips)
    precips2 <- NULL#cent$precips2
    #if (!is.null(precips2)) precips2 <- unwrap(precips2)[[1]] ###  for ecmwf, the precips2 only has one layer, so cant subset with [[1]]. others?
    cent <- cent$cent
  }
  times = unique(cent$date[!is.na(cent$date)])
  mintime <- cent$mindate
  maxdate <- cent$maxdate
  id <- unique(cent$ID[!is.na(cent$ID)])
  ###  add in the first hour of the next day for interpolation
  if (!is.null(precips2)) precips_p <- suppressWarnings(project(c(precips,rast(precips2)),unwrap(r)))
  else precips_p <- suppressWarnings(project(precips,unwrap(r)))
  ##  get the timestep
  dt <- unique(difftime(times,dplyr::lag(times),unit="hour"))
  dt <- as.numeric(dt[!is.na(dt)])
  ###  add in missing times to be approximated
  notimes <- unique(times[!times %in% terra::time(precips_p)])
  ###  convert to the right delta time
  ###  also, ecmwfr is in meters, convert to mm
  if (source=="ecmwf") precips_p <- precips_p*dt
  ###  the mswep totals are per 3 hours in mm
  if (source=="mswep") precips_p <- (precips_p/3)*dt
  ##   the gpm data are half hourly but the rate is still mm/hr and already in mm
  if (source=="gpm") precips_p <- (precips_p)*dt
  ###  the native layers are named accordingly, before interpolation
  names(precips_p)= rep(paste0(source,"_precip.mm/",dt,"hr_native"),nlyr(precips_p))
  ###  interpolate the in-between times
  if (length(notimes)>0){
    precips_notimes <-  rep(unwrap(r),length(notimes))
    terra::time(precips_notimes) <- notimes
    ###  name the interpolated layers
    names(precips_notimes)= rep(paste0(source,"_precip.mm/",dt,"hr_interp"),nlyr(precips_notimes))
    precips_all <- c(precips_p,precips_notimes)
    precips_all <- precips_all[[order(terra::time(precips_all))]]
    ##  approximate the values in between the endpoints
    ##  if time(x) is accurate, the approximation will use it for distance
    precips_all <- approximate(precips_all)
  }else{
    precips_all <- precips_p
  }
  terra::units(precips_all) <- paste0("mm/",dt,"hr")
  ## when running in parallel, each iteration's last layer is the first layer from the next iteration, so remove it. except for the last iteration...
  if (!is.null(cent$maxdate)&&!any(cent$maxdate %in% cent$date)) precips_all <- precips_all[[-nlyr(precips_all)]]

  return(wrap(precips_all))
}
pre_sub_precips <- function(prcips,stormpoints,prehours,cpus=NULL){
  #pnts <- as.data.frame(app(prcips,"mean",na.rm=TRUE),xy=TRUE)
  #pnts <- pnts%>%st_as_sf(coords=c("x","y"),crs=crs(prcips))
  ### rains start about 500km out, so find the track that first gets within 500km of a point
  ###  then find the last track that is within 500km of a point, those are the start and end points for the storm precip.
  #rains <- stormpoints|>filter(date>=min(date[!is.na(ID)],na.rm=TRUE))|> st_buffer(500000)
  #rains <- sf::st_covered_by(pnts,rains)
  #rainstart <- lapply(rains,function(x) ifelse(length(x)==0,NA,min(x)))
  #rainsend <- lapply(rains,function(x) ifelse(length(x)==0,NA,max(x)))
  #pnts$start <- unlist(rainstart)
  #pnts$end <- unlist(rainsend)
  #pnts <- st_transform(pnts,crs(prcips))
  #start <- rasterize(pnts,prcips[[1]],field="start")
  #end <- rasterize(pnts,prcips[[1]],field="end")
  #dt <- as.numeric(unique(stormpoints$dt[!is.na(stormpoints$dt)]))
  prcips <- prcips[[order(terra::time(prcips))]]
  matchtimes <-  match(stormpoints|>filter(date>=minstormdate)|> pull(date),terra::time(prcips))
  #start_storm  <- app(start,function(x,y) y[x],y=matchtimes)
  #end_storm <- app(end,function(x,y) y[x],y=matchtimes)
  pre_rasts <- list()
  ###  parallelization difficult because every worker node needs a copy of the full set of rasters...
  if (!is.null(cpus)){
    prcips_pre <- wrap(prcips)
    matchtimes <- split(matchtimes,cut(seq_along(matchtimes), cpus, labels = FALSE))
    on.exit(sfStop())
    sfInit(parallel=TRUE,cpus=cpus)#,slaveOutfile= "C:/Users/BenjaminBranoff/Downloads/paralleltesting.txt")
    sfLibrary(terra)
    sfLibrary(sf)
    sfLibrary(dplyr)
    sfLibrary(snowfall)
  }
  for (pr in prehours){
    #start_pre <- app(start,function(x,y) y[x]+pr/dt,y=matchtimes)
    ###  crop (mask) the files according to the start and end times
    if (is.null(cpus)){
      prcips_cropped <- lapply(seq_along(matchtimes), function(x){
        i=x
        x=matchtimes[x]
        ###  first mask out the area ahead of the storm
        prcips_pre <- mask(prcips[[time(prcips)==time(prcips[[x]])]],
                           stormpoints|>filter(date>=time(prcips[[x]]),date<time(prcips[[x]])+pr*60*60)|>st_buffer(500000))
        ###  then the area where the storm currently is
        prcips_pre <- mask(prcips_pre,stormpoints|>filter(date==time(prcips[[x]]))|>st_buffer(500000),inverse=TRUE)
        names(prcips_pre) <- gsub("precip.mm",paste0(pr,"hrsprestormprecip.mm"),names(prcips[[x]]))

        cat(paste0("\rcalculating prestorm precip: %", round(100*i/length(matchtimes))))
        if (!is.na(terra::minmax(prcips_pre)[1])) prcips_pre
        else NULL
      })
      prcips_cropped <- rast(prcips_cropped)
      cat("\n")
    }else{
      # ###  parallel VERY slow
      # browser()
      # matchtimes_p <- lapply(matchtimes, function(x){
      #   r <- prcips[[time(prcips) %in% time(prcips[[x]])-pr*60*60]]
      #   pt <- stormpoints|>filter(date>=min(time(r)),date<max(time(r)+pr*60*60))|>st_buffer(500000)
      #   list(points=pt,rast=wrap(r))
      # })
      # prcips_cropped <- sfLapply(matchtimes_p, function(x,p){
      #   prcipspre <- unwrap(x$rast)
      #   pts <- x$points
      #   prcips_pre <- lapply(1:nlyr(prcipspre),function(y,pp,pt,p){
      #     p_p <- mask(pp[[y]],pt|>filter(date>=time(pp[[y]]),date<time(pp[[y]])+p*60*60))
      #     names(p_p) <- gsub("precip.mm","prestormprecip.mm",names(pp[[y]]))
      #     if (!is.na(terra::minmax(p_p)[1])) return(p_p)
      #     else return(NULL)
      #   },pp=prcipspre,pt=pts,p=p)
      #   prcips_pre <- Filter(Negate(is.null), prcips_pre)
      #   prcips_pre <- rast(prcips_pre)
      #   return(wrap(prcips_pre))
      # },p=pr)

    prcips_cropped <- rast(lapply(prcips_cropped,unwrap))
    prcips_cropped <- prcips_cropped[[order(terra::time(prcips_cropped))]]
    }
    pre_rasts <- append(pre_rasts,list(prcips_cropped))
  }
  names(pre_rasts) <- paste0("prestorm_precip_",prehours,"_hrs")
  pre_rasts
}

deliver_precip <- function(precips_all,cent,pre_storm,todir,source,overwrite,loadrsts,cpus,ex_parallel){
  ###  some requests get a full day at a time, trim the end days to drop times when the storm is non-existent
  if (any(terra::time(precips_all)>=unique(cent$minstormdate))){
    precips_storm <- precips_all[[terra::time(precips_all) %in% (cent|>filter(date>=unique(minstormdate))|>pull(date))]]
    precips_storm <- rast(lapply(1:nlyr(precips_storm),function(x) mask(precips_storm[[x]], st_buffer(cent[which(cent$date==terra::time(precips_storm[[x]])),],500000))))
  }else{
    precips_storm <- precips_all
  }
  ###  separate the prestorm layers from the storm layers
  if (!is.null(pre_storm)){
    precips_prestorm <- pre_sub_precips(precips_all,cent,pre_storm,cpus=NULL)
    #else precips_prestorm <- list(wrap(precips_all));precips_storm <- if(is.null(precips_storm)) NULL else {wrap(precips_storm)}#precips_all[[!terra::time(precips_all) %in% terra::time(precips_storm)]]
    precips_all <- list(storm=precips_storm,prestorm=precips_prestorm)
    prefiles <- lapply(seq_along(pre_storm),function(x) paste0(todir,"/",source,"_",unique(cent$ID),"_",format(time(unwrap(precips_prestorm[[x]])),"%Y%m%d%H%M"),"_",pre_storm[x],"hrs_prestorm.tif"))
  }else{
    #if (prll) precips_storm <- if(is.null(precips_storm)) NULL else {wrap(precips_storm)}
    precips_all <- list(storm=precips_storm)
    prefiles <- NULL
  }
  tofiles <- paste0(todir,"/",source,"_",unique(cent$ID),"_",format(time(unwrap(precips_storm)),"%Y%m%d%H%M"),".tif")
  ###  only keep the files that arent already saved if overwrite is FALSE?
  ### can only do this if out of parallel
  ### for parallel, saving is done once all files are assembled
  if (!is.null(todir)){
    if (!overwrite){
      if (!is.null(precips_storm)&&!all(file.exists(tofiles))) {
        precips_storm <- unwrap(precips_storm)[[!file.exists(tofiles)]]
        writeRaster(precips_storm,tofiles[!file.exists(tofiles)],overwrite=overwrite)
      }
      if (!is.null(pre_storm)) lapply(seq_along(pre_storm),function(x){
        if (!all(file.exists(prefiles[[x]]))){
          writeRaster(unwrap(precips_prestorm[[x]])[[!file.exists(prefiles[[x]])]],
                      prefiles[[x]][!file.exists(prefiles[[x]])],overwrite=overwrite)
        }
      })
      #else if(!file.exists(prefiles)) writeRaster(unwrap(precips_prestorm),prefiles,overwrite=overwrite)
      ##  only one prefile, so no need to include here..unless we want to do it for every prestorm period...
    }else{
      writeRaster(unwrap(precips_storm),tofiles,overwrite=overwrite)
      if (!is.null(pre_storm)) lapply(seq_along(pre_storm),function(x){
        #prefilesx <- grep(pre_storm[x],prefiles,value=TRUE)
        writeRaster(unwrap(precips_prestorm[[x]]),prefiles[[x]],overwrite=overwrite)
      })
    }
  }
  if (loadrsts|is.null(todir)){
    if (ex_parallel) return(rapply(precips_all,wrap))
    else(return(precips_all))
  }
  else return(Filter(Negate(is.null),c(tofiles,unlist(prefiles))))
}
load_precip <- function(storm,todir,loadrasts){
  if (is.null(todir)){
    todir=getwd()
  }
  meths <- list.dirs(paste0(todir,"/",storm,"/"))[-1]
  precips = list.files(paste0(todir,"/",storm,"/"),recursive = TRUE,full.names = TRUE,pattern=".tif")
  if (length(precips)==0) stop("No .tif files found in supplied directory. Do you need to specify the todir?")
  out <- list()
  for (m in meths){
    precips = list.files(m,recursive = TRUE,full.names = TRUE,pattern=".tif")
    if (length(precips)>0){
      #nmes <- gsub(".tif","",basename(precips))
      storm = grep("prestorm",precips,invert=TRUE,value=TRUE)
      if (any(grepl("prestorm",precips))){
        prestorm = grep("prestorm",precips,value=TRUE)
        pretimes <- unique(sapply(strsplit(prestorm,"_"),"[[",10))
        prestorm = setNames(lapply(pretimes,function(x) grep(x,prestorm,value=TRUE)),paste0("prestorm_precip_",pretimes))
      }else{
        prestorm=NULL
      }
      if (loadrasts){
        storm = rast(storm)
        prestorm <- lapply(prestorm,rast)
      }
      out <- append(out,list(list(storm=storm,prestorm=prestorm)))
    }
  }
  names(out) <- basename(meths)
  return(out)#setNames(list(out),paste(strsplit(precips[[1]],"_")[[1]][c(5:8)],collapse ="_")))
}
